### PR TITLE
Fix in ext.py (index error on system without GPU)

### PR DESCRIPTION
**Pull request by MischaPanch**
Without this exllamav2 can't even be imported on a system without GPU:

```
...python3.11/site-packages/exllamav2/ext.py:43: in maybe_set_arch_list_env
    arch_list[-1] += '+PTX'
E   IndexError: list index out of range
```

### CODE REVIEW

**Comment by turboderp** [comment]
Thanks. Next version coming soon, I'll include this.

**Comment by MischaPanch** [comment]
Great, thanks! :)

**Comment by bartowski1182** [comment]
Just for curiousity, what can you do with exl2 with no GPU? Only ask in case I'm missing a use case lol

**Comment by MischaPanch** [comment]
Nothing really, and there's another error on import after this one is fixed. 

But the failure should not happen at import time. This makes it impossible (or rather cumbersome, as every import now needs try-except) to include exllama in code that is tested on non-gpu machines, in particular in CI.

**Comment by bartowski1182** [comment]
Ahhhh CI wasn't something I considered, thanks for the info :)

**Pull request merged**
