### PR TITLE
Fixed multi file and wildcard args

### PR DESCRIPTION
**Pull request by SinanAkkoyun**
Before it couldn't handle wildcard args for me

### CODE REVIEW

**Comment by bartowski1182** [comment]
@SinanAkkoyun can you provide an example of inputting wildcards? This change seems to have broken wildcard input for me

**Comment by bartowski1182** [comment]
Reverting this commit fixes wildcard input for me:

python3 utils/convert_safetensors.py /models/model_name/pytorch*.bin

**Comment by turboderp** [comment]
Interesting. What shell are you using?

**Comment by bartowski1182** [comment]
Just Linux bash

**Comment by bartowski1182** [comment]
@SinanAkkoyun any info on how you're using this? I'm still reverting this merge for my use case because I can't convert with wildcards anymore.

**Comment by bartowski1182** [comment]
@turboderp do you mind reverting this commit? If this was fixing a real issue I can look at a better fix but for now it's frustrating that it broke wildcard support

**Comment by SinanAkkoyun** [comment]
@bartowski1182 That's odd, for me it works with simply specifying: `python3 utils/convert_safetensors.py /models/model_name/pytorch*` (I can not try it out now, I do not have access to my machine atm)

It seems as if the PR only breaks for your environment, if that's the case you could simply copy the old util script into another directory and run it there to convert

**Comment by bartowski1182** [comment]
@SinanAkkoyun is that how you would use it? I can't imagine how it would work with a wildcard from the code, since you just run for file in args.input_files:, that doesn't seem to handle using a wildcard at all but would work with a list of files

**Comment by SinanAkkoyun** [comment]
Idk how but my PR worked for me, perhaps my shell handled that

**Comment by SinanAkkoyun** [comment]
I can retry in a couple of weeks when I get access to my machine

**Comment by SinanAkkoyun** [comment]
Just set a simplified version up on the go, tested the input file arg parsing, works fine for fish and bash (ubuntu 20.04)

with * at the end, with *.bin at the end, all work flawlessly

**Comment by turboderp** [comment]
It also works for me (bash). Previously you'd have to run it like `python convert_safetensors.py "*.bin"` since otherwise `*.bin` would be expanded by the shell to a list of files matching the pattern. Adding `nargs='+'` correctly catches that list and so wildcard matching can be done by the shell.

What happens if you run this?

```python
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("filenames", nargs="+", type=str)
args = parser.parse_args()
print(args.filenames)
```

**Comment by bartowski1182** [comment]
I've isolated the problem a bit

If I run the code directly from my terminal, it works

If I run it inside a docker container, it doesn't..

I'm not sure how running from a docker container is making it not work, it doesn't make any sense to behave differently, but now that I know what I'm looking for I should have an easier time either figuring out what's broken or figuring out how to fix this code so that it works in both scenarios

**Comment by bartowski1182** [comment]
Made a fix for it, seems that docker commands won't expand wildcard files like regular bash does, will now work for both:

https://github.com/turboderp/exllamav2/pull/344

**Pull request merged**
