### PR TITLE
Fix compiling and running on ROCm HIP

### PR DESCRIPTION
**Pull request by ardfork**
I only tested with a GPTQ model, haven't tested EXL2 yet.

### CODE REVIEW

**Comment by ardfork** [comment]
Here are some benchmark on a 13B GPTQ (128g) with a 6700 XT:
```
 -- Measuring prompt speed...
 ** Length   128 tokens:    355.7812 t/s
 ** Length   256 tokens:    604.9509 t/s
 ** Length   384 tokens:    601.7808 t/s
 ** Length   512 tokens:    670.5597 t/s
 ** Length   640 tokens:    619.4336 t/s
 ** Length   768 tokens:    655.6445 t/s
 ** Length   896 tokens:    650.2208 t/s
 ** Length  1024 tokens:    678.5568 t/s
 ** Length  1152 tokens:    653.1508 t/s
 ** Length  1280 tokens:    623.2556 t/s
 ** Length  1408 tokens:    595.5416 t/s
 ** Length  1536 tokens:    590.4946 t/s
 ** Length  1664 tokens:    569.0113 t/s
 ** Length  1792 tokens:    562.0255 t/s
 ** Length  1920 tokens:    538.2682 t/s
 ** Length  2048 tokens:    556.7499 t/s
 -- Measuring token speed...
 ** Position     1 + 127 tokens:   35.9594 t/s
 ** Position   128 + 128 tokens:   35.5533 t/s
 ** Position   256 + 128 tokens:   34.5516 t/s
 ** Position   384 + 128 tokens:   33.9032 t/s
 ** Position   512 + 128 tokens:   32.9328 t/s
 ** Position   640 + 128 tokens:   31.7120 t/s
 ** Position   768 + 128 tokens:   31.6832 t/s
 ** Position   896 + 128 tokens:   31.6106 t/s
 ** Position  1024 + 128 tokens:   30.9029 t/s
 ** Position  1152 + 128 tokens:   29.8211 t/s
 ** Position  1280 + 128 tokens:   29.0312 t/s
 ** Position  1408 + 128 tokens:   28.1710 t/s
 ** Position  1536 + 128 tokens:   27.4993 t/s
 ** Position  1664 + 128 tokens:   27.0346 t/s
 ** Position  1792 + 128 tokens:   26.7067 t/s
 ** Position  1920 + 128 tokens:   26.1313 t/s
```
Compared to exllama v1:
```
 ** Time, Inference: 3.69 seconds
 ** Speed: 520.52 tokens/second
 -- Generating 128 tokens, 1920 token prompt...
 ** Speed: 13.87 tokens/second
 -- Generating 128 tokens, 4 token prompt...
 ** Speed: 28.87 tokens/second
```

**Comment by turboderp** [comment]
This is excellent, thank you. I'm out of time for today, I think, so I'll be a few hours before I can check if this all still plays well with NVIDIA, then I'll merge.

**Comment by ardfork** [comment]
Also tested with https://huggingface.co/turboderp/Llama2-7B-5.0bpw-h6-exl2, everything seems to work correctly. But, I cannot test multi gpu.

**Comment by lookfirst** [comment]
@ardfork sorry to spam this issue, but i couldn't find any other contact for you. can you please reach out to me at lookfirst619@gmail.com? i'd like to chat with you about your excellent rocm work. thanks!

**Pull request merged**
