### PR TITLE
Add LLM-FTC-sampling

### PR DESCRIPTION
**Pull request by catid**
Implements the idea here: http://antirez.com/news/142

### CODE REVIEW

**Comment by catid** [comment]
Seems to improve the ability for Mixtral model to reason on my TextWorld benchmark by a statistically significant margin: https://x.com/MrCatid/status/1746308698887147626?s=20

**Comment by turboderp** [comment]
I'm sorry, but is this not pretty much identical to min-P?

**Comment by catid** [comment]
You'd know better than me.  I think the author of the blog post acknowledges that it's the same thing

**Comment by catid** [comment]
Random unrelated question for you @turboderp : Is there some way to get these temp_probe values at the API level?  I have a use for them for a project I'm working on.

**Pull request closed without merging**
