### PR TITLE
Kalomaze's Quadratic Sampling

### PR DESCRIPTION
**Pull request by AAbushady**
Quadratic Sampling

### CODE REVIEW

**Comment by test157t** [comment]
I don't have any capacity to make decisions here, but i approve.

**Comment by turboderp** [comment]
I think an exponent of 2.3 works better than 2. Change my mind.

**Comment by AAbushady** [comment]
I know I know, but this one is good, a lot of people have tested it. I do need to make a change after I'm done with work today though so OOP is sub-optimal for quad sampling application. So more to come there.

**Comment by AAbushady** [comment]
Okay, updates are made!

**Comment by frammiie** [comment]
This one is huge boss! 💪

**Comment by test157t** [comment]
Guess i drop both both tabby and exl2 until is implemented, just like the frog... off to the shadow realms with ye.

**Comment by turboderp** [comment]
So there. With a secret cubic sampling option for those brave enough to seek it out.

**Pull request merged**
